[package]
name = "yusuf/blackboard"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "0.1.0"

[dependencies]
Roact = "roblox/roact@1.4.4"
RoactRodux = "roblox/roact-rodux@0.3.0"
Rodux = "roblox/rodux@3.0.0"
